src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity (
 *  fields={"username"},
 *  message="Le nom d'utilisateur que vous avez entré est déjà utilisé"
 * )
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [''];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(min="8", minMessage="Votre mot de passe doit faire minimum 8 caractères")
     * @Assert\EqualTo(propertyPath="confirm_password", message="Votre mot de passe doit être identitique")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Votre mot de passe doit être identitique")
     */
    public $confirm_password;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Page de connexion</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('adminlte/dist/css/adminlte.min.css') }}">
</head>
<style>
    .login-page, .register-page {
        background-image: url("{{ asset('adminlte/dist/img/login-bg.jpg') }}") !important;
    }
    .form-control, .input-group-text {
        border-top: none !important;
        border-right: none !important;
        border-left: none !important;
        border-bottom: 1px solid #ced4da !important;
    }
    .login-box {
        box-shadow: 10px 10px 20px gray !important;
    }
    .mylogin-btn {
        color: #fff;
        background: #2469D8;
        border-color: #2469D8;
    }
    .mylogin-btn:hover {
        color: #fff;
        background: #1b53ae;
        border-color: #184896;
    }
    
</style>
<body class="hold-transition login-page">
{% block body %}
<div class="login-box">
    <div class="login-logo">
        <a href=""><b>Système de logistique des camions</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Veuillez vous connecter</p>

            {% if error %}
                <span class="invalid-feedback d-block mb-3">
                    <span class="d-block">
                        <span class="form-error-icon badge badge-danger text-uppercase">Erreur</span>
                            <span class="form-error-message">{{ error.messageKey|trans(error.messageData, 'security') }}</span>
                    </span>
                </span>
            {% endif %}

            {% if app.user %}
                <div class="d-block mb-3">
                    <span class="d-block">
                        <span class="badge badge-info text-uppercase">Info</span>
                            <span>
                            <span class="small">Vous êtes déjà connecté en tant que {{ app.user.userIdentifier }}, </span>
                                <a href="{{ path('app_logout') }}">Se déconnecter</a>
                            </span>
                    </span>
                </div>
            {% endif %}
            <form method="post">
                <div class="input-group mb-3">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                    <input type="text" value="{{ last_username }}" name="username" id="inputUsername" class="form-control" placeholder="Nom d'utilisateur">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                    <input type="password" name="password" id="inputPassword"  class="form-control" placeholder="Mot de passe">
                    <input type="hidden" name="_csrf_token"
                           value="{{ csrf_token('authenticate') }}"
                    >
                </div>
                <div class="row">

                    <!-- /.col -->
                    <div class="col-3"></div>
                    <div class="col-6">
                        <button type="submit" class="btn mylogin-btn btn-block">Se connecter</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
            <!-- /.social-auth-links -->
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
<!-- /.login-box -->
{% endblock %}
<!-- jQuery -->
<script src="{{ asset('adminlte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('adminlte/dist/js/adminlte.min.js') }}"></script>
</body>
</html>

templates/security/registration.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block stylesheets %}
<style>
    label.col-form-label.col-sm-2.required{
        max-width: 100% !important;
        flex: 0 0 100% !important;
    }
    input[type="search"] {
        width: 0% !important;
    }
    .form-control {
        width: 120% !important;
    }
    .user-open {
        background-color: #2469D8 !important;
    }
    .user-open:hover {
        background-color: #1b53ae !important;
    }
</style>
{% endblock %}

{% block content_wrapper %}
<div class="content-wrapper">
    <section class="content">
        <div class="register-box register-box mt-0 ml-auto mr-auto w-50">
            <div class="card card-outline card-primary">
                <div class="card-header text-center">
                <a href="#" class="h1">Ajouter une nouvelle utilisateur</a>
                </div>
                <div class="card-body">
                <p class="login-box-msg">Veuillez complètez les champs</p>
                {{ form_start(form) }}
                    {{ form_row(form.username, {'label': 'Nom d\'utilisateur', 
                                                'attr': {
                                                    'placeholder': 'Nom d\'utilisateur',
                                                    'autocomplete': 'false'
                                                    }
                                                }
                                )
                    }}
                    {{ form_row(form.password, {'label': 'Mot de passe', 
                                                'attr': {
                                                    'placeholder': 'Mot de passe',
                                                    'autocomplete': 'false'
                                                    }
                                                }
                                )
                    }}
                    {{ form_row(form.confirm_password, {'label': 'Confirmation votre mot de passe', 
                                                'attr': {
                                                    'placeholder': 'Répétez votre mot de passe',
                                                    'autocomplete': 'false'
                                                    }
                                                }
                                )
                    }}
            

                <div class="social-auth-links text-center">
                    <button class="btn btn-block btn-primary" type="submit">Inscription</button>
                </div>
                <!-- /.form-box -->{{ form_end(form) }}
            </div><!-- /.card -->
        </div>
        <!-- /.register-box -->
    </section>
</div>
{% endblock %}